
# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database-service
  labels:
    app: database
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer   # ⭐ Yeh line add ki gayi hai
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: database
    release: {{ .Release.Name }}

